---
- name: 1) 패키지 설치(web/db)
  ansible.builtin.dnf:
    name:
      - "{{ ansible_local.custom.packages.pkg_db }}"
      - "{{ ansible_local.custom.packages.pkg_web }}"
    state: latest

- name: 2) 서비스 기동(web/db)
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - "{{ ansible_local.custom.services.svc_db }}"
    - "{{ ansible_local.custom.services.svc_web }}"

- name: 3) 웹 서버 설정 - index.html
  ansible.builtin.copy:
    content: "{{ ansible_fqdn}} : {{ ansible_all_ipv4_addresses }}"
    dest: "{{ webroot }}/index.html"
    mode: '0644'
