---
- name: 복원작업 - intranet.yml
  hosts: all
  tasks:
    - name: 방화벽에서 웹 서비스 제거
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled

    - name: 파일 삭제 - index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 웹 패키지 삭제
      ansible.builtin.yum:
        name: httpd
        state: absent
