---
- name: "아파치 웹 서버 설치 및 기동"
  hosts: webservers
  tasks:
    - name: "1) 패키지 설치"
      ansible.builtin.dnf:
        name: httpd
        state: latest
    - name: "2) 웹 서비스 설정"
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
    - name: "3) 웹 서비스 기동"
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
    - name: "4) 방화벽에 등록"
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
